rm ./after/plugin/snipMate.vim
rm ./autoload/snipMate.vim
rm ./doc/snipMate.txt
rm ./ftplugin/html_snip_helper.vim
rm ./plugin/snipMate.vim
rm ./plugin-info.txt
rm ./README.markdown
rm ./snippets/_.snippets
rm ./snippets/autoit.snippets
rm ./snippets/c.snippets
rm ./snippets/cpp.snippets
rm ./snippets/erlang.snippets
rm ./snippets/html.snippets
rm ./snippets/java.snippets
rm ./snippets/javascript.snippets
rm ./snippets/mako.snippets
rm ./snippets/objc.snippets
rm ./snippets/perl.snippets
rm ./snippets/php.snippets
rm ./snippets/python.snippets
rm ./snippets/ruby.snippets
rm ./snippets/sh.snippets
rm ./snippets/snippet.snippets
rm ./snippets/tcl.snippets
rm ./snippets/tex.snippets
rm ./snippets/vim.snippets
rm ./snippets/zsh.snippets
rm ./syntax/snippet.vim
